package aplicacion.modelo.dominio;
// Generated 08/06/2019 10:53:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categorias generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int idcategoria;
     private String nombre;
     private String descripcion;
     private Set productos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(int idcategoria) {
        this.idcategoria = idcategoria;
    }
    public Categoria(int idcategoria, String nombre, String descripcion, Set productoses) {
       this.idcategoria = idcategoria;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.productos = productoses;
    }
   
    public int getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(int idcategoria) {
        this.idcategoria = idcategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


