package aplicacion.modelo.dominio;
// Generated 08/06/2019 10:53:24 by Hibernate Tools 4.3.1



/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private int iddetalle;
     private Factura factura;
     private Producto producto;
     private Integer cantidad;
     private String precioProdCant;

    public Detalle() {
    }

	
    public Detalle(int iddetalle, Factura factura, Producto productos) {
        this.iddetalle = iddetalle;
        this.factura = factura;
        this.producto = productos;
    }
    public Detalle(int iddetalle, Factura factura, Producto productos, Integer cantidad, String precioProdCant) {
       this.iddetalle = iddetalle;
       this.factura = factura;
       this.producto = productos;
       this.cantidad = cantidad;
       this.precioProdCant = precioProdCant;
    }
   
    public int getIddetalle() {
        return this.iddetalle;
    }
    
    public void setIddetalle(int iddetalle) {
        this.iddetalle = iddetalle;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public String getPrecioProdCant() {
        return this.precioProdCant;
    }
    
    public void setPrecioProdCant(String precioProdCant) {
        this.precioProdCant = precioProdCant;
    }




}


