package aplicacion.modelo.dominio;
// Generated 08/06/2019 10:53:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private int numFactura;
     private Modopago modopago;
     private Usuario usuario;
     private Date fecha;
     private Set detalles = new HashSet(0);

    public Factura() {
    }

	
    public Factura(int numFactura, Modopago modopago, Usuario usuarios) {
        this.numFactura = numFactura;
        this.modopago = modopago;
        this.usuario = usuarios;
    }
    public Factura(int numFactura, Modopago modopago, Usuario usuarios, Date fecha, Set detalles) {
       this.numFactura = numFactura;
       this.modopago = modopago;
       this.usuario = usuarios;
       this.fecha = fecha;
       this.detalles = detalles;
    }
   
    public int getNumFactura() {
        return this.numFactura;
    }
    
    public void setNumFactura(int numFactura) {
        this.numFactura = numFactura;
    }
    public Modopago getModopago() {
        return this.modopago;
    }
    
    public void setModopago(Modopago modopago) {
        this.modopago = modopago;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }




}


